#!/bin/bash

export DYLD_LIBRARY_PATH=`pwd`
echo "export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"

export DYLD_INSERT_LIBRARIES='libft_malloc.so'
echo "export DYLD_INSERT_LIBRARIES=$DYLD_INSERT_LIBRARIES"

export DYLD_FORCE_FLAT_NAMESPACE=1
echo "export DYLD_FORCE_FLAT_NAMESPACE=$DYLD_FORCE_FLAT_NAMESPACE"
